version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./log/traefik:/log/traefik"
      - "./traefikData/traefik.yml:/traefik.yml"
      - "./traefikData/dynamic.yml:/dynamic.yml"
      - "/etc/localtime:/etc/localtime:ro"


  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.$DOMAIN`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

# Zum testen wird erst einmal der Root genutzt, das muss sp채ter unbedingt ge채ndert werden!!!
  db:
    depends_on: 
      -  traefik 
    image:  linuxserver/mariadb:arm32v7-latest 
    container_name:  wp_mariadb 
    volumes:
      -  $DBDATA:/config 
    environment:
      TZ:  Europe/Berlin 
      MYSQL_ROOT_PASSWORD: $DBPASSWD 
      MYSQL_DATABASE:  wordpress 
      #MYSQL_USER: $MYSQL_USER 
      #MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      -  3306:3306 
    networks:
      -  default 
    restart:  unless-stopped 


# Zum testen wird erst einmal der Root genutzt, das muss sp채ter unbedingt ge채ndert werden!!!
  wp:
    depends_on: 
      -  db 
    links: 
      -  db 
      -  db:wp_mariadb   
    image:  wordpress:latest 
    container_name:  wordpress 
    volumes:
      -  $WPDATA:/var/www/html 
    environment:
      WORDPRESS_DB_HOST:  db:3306 
      #WORDPRESS_DB_USER:  root 
      WORDPRESS_DB_PASSWORD: $DBPASSWD 
      WORDPRESS_DB_NAME:  wordpress       
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp.rule=Host(`$DOMAIN`, `wordpress.$DOMAIN`, `www.$DOMAIN`)"
      - "traefik.http.routers.wp.entrypoints=websecure"
      - "traefik.http.routers.wp.tls.certresolver=myresolver"

    networks:
      -  default 
      -  web 
    restart:  unless-stopped 


networks:
  web:
    external: true
